version: '3.8'

services:
  postgres-15.3:
    build:
      context: ./build/postgres15.3
      args:
        - ID_USER=${ID_USER:-1000}
        - ID_GROUP=${ID_GROUP:-1000}
    volumes:
      - './volumes/postgres15.3:/var/lib/postgresql/data'
    ports:
      - '${FORWARD_DB_PORT_15_3:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE:-test}'
      POSTGRES_USER: '${DB_USERNAME:-pguser}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    restart: unless-stopped

  postgres-11.20:
    build:
      context: ./build/postgres11.20
      args:
        - ID_USER=${ID_USER:-1000}
        - ID_GROUP=${ID_GROUP:-1000}
    volumes:
      - './volumes/postgres11:/var/lib/postgresql/data'
    ports:
      - '${FORWARD_DB_PORT_11:-5433}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE:-test}'
      POSTGRES_USER: '${DB_USERNAME:-pguser}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    restart: unless-stopped
