version: '3.8'

services:
  postgres-15.3:
    build:
      context: ./build/postgres15.3
    volumes:
      - './volumes/postgres15.3:/var/lib/postgresql/data'
    ports:
      - '${FORWARD_DB_PORT_15_3:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE:-test}'
      POSTGRES_USER: '${DB_USERNAME:-pguser}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    restart: unless-stopped

  postgres-11:
    build:
      context: ./build/postgres11
    volumes:
      - 'postgres11:/var/lib/postgresql/11/main'
    ports:
      - '${FORWARD_DB_PORT_11:-5433}:5432'
    restart: unless-stopped
    command: bash -c "service postgresql start && tail -F anything"
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  postgres11:
